#for your build environment.
image: qdata/qciagent

pipelines:
    branches: #The branch section is a container for all branch-specific pipelines
        master:
            - step:
                script:
                    - export HOST='ftp.ord1-1.websitesettings.com'
                    - export TARGETFOLDER='/web/content'
                    - export SOURCEFOLDER='.'
                    - export FTPUSER=$FTPUSER
                    - export FTPPSWD=$FTPPSWD
                    - rm --recursive -f node_modules
                    - /bin/bash /deploy.bash
        stage:
            - step:
                script:
                    - export STGFTPUSER=$STGFTPUSER
                    - export STGFTPPSWD=$STGFTPPSWD
                    - export STGFTPHOST=$STGFTPHOST
                    - export STGDESTFOLDER=$STGDESTFOLDER
                    - rm --recursive -f node_modules
                    - python -V
                    - python /cmdtools/deploytools/deploy.py -v -un -m ftp -u $STGFTPUSER -p $STGFTPPSWD -s $STGFTPHOST -f $STGDESTFOLDER -g .
                    - echo "Desplegado en stage"
    default:
        - step:
            script:
                - echo "Running on the default job"